#Dicionário geral

tk01 = "while"
tk02 = "= ["
tk03 = "=["
tk04 = "for"
tk05 = " +"
tk06 = "-"
tk07 = "*"
tk08 = "/"
tk09 = "//"
tk10 = "%"
tk11 = "**"
tk12 = "=="
tk13 = "if"
tk14 = "="
tk15 = ".add "
tk16 = " bin"
tk17 = " dict"
tk18 = ".discard"
tk19 = " float"
tk20 = " input"
tk21 = " int"
tk22 = " len"
tk23 = ".pop"
tk24 = " print"
tk25 = " sorted"
tk26 = " str"
tk27 = " append"
tk28 = " exit"
tk29 = "def "
tk30 = "lambda"
tk31 = " class "
tk32 = "break"
tk33 = "++"


log001 = "Loop opening with WHILE"
log002 = "Worked with a list or vector"
log003 = "Worked with a list or vector"
log004 = "Loop opening with FOR"
log005 = "Operator: sum or concatenation of string"
log006 = "Operator: subtraction or complementation of a set"
log007 = "Operator: multiplication"
log008 = "Operator: division int, float, result float or complex"
log009 = "Operator: division int, results int or float by int or float only whole part"
log010 = "nt rest of the ints division, entire part if floats division"
log011 = "Potentiation of int, float or complex"
log012 = "Tests for equality of int, float complex or string, results True or False"
log013 = "Conditional imposed"
log014 = "Value assignment"
log015 = "Inserting element in a set"
log016 = "Conversion of int to binary"
log017 = "Implementation of ordered data structure"
log018 = "Removal of set element"
log019 = "Conversion to Float"
log020 = "Inserts an input value of data in the form of a string"
log021 = "Conversion to Int"
log022 = "Return with the number of elements in the string"
log023 = "Removing an element from the list"
log024 = "On-screen data output"
log025 = "List naming"
log026 = "Conversion to string"
log027 = "List concatenation"
log028 = "Execution ends"
log029 = "Function definition"
log030 = "Lambda function found"
log031 = "Class created"
log032 = "Interruption"
log033 = "Value addition in variable"
